#define IDI_ICON                6666
#define IDB_RAEDITBUTTON        100
#define IDC_HSPLITTCUR          101
#define IDB_BOOKMARK            102
#define IDC_SELECTCUR           103
#define IDB_LINENUMBER          104
#define IDB_EXPAND              105
#define IDB_COLLAPSE            106
#define IDB_LOCK                107
#define RC_KEYWORDS             108
#define RC_WINAPI               109
